### ISSUE TITLE
Just doesn't start with error

### ISSUE THREAD

**Issue by VyacheslavLukin** [innosoft-pro/toggl-youtrack-auto-time#26]
That's it
![image](https://user-images.githubusercontent.com/7655121/30520502-b927d90e-9bb7-11e7-98cf-85ac30b0080e.png)

**Comment by AleksandrShepelev** [comment]
https://askubuntu.com/questions/907035/importerror-cannot-import-name-remove-dead-weakref
https://ru.stackoverflow.com/questions/637908/importerror-cannot-import-name-remove-dead-weakref-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-%D0%BF%D1%80%D0%B8-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B5-pyth

**Comment by VyacheslavLukin** [comment]
:+1:
